# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclasses.proto\"E\n\x05\x41luno\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x0c\n\x04Nome\x18\x02 \x01(\t\x12\x0f\n\x07Periodo\x18\x03 \x01(\x05\x12\x11\n\tCod_curso\x18\x04 \x01(\x05\"!\n\x05\x43urso\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04Nome\x18\x02 \x01(\t\"P\n\nDisciplina\x12\x0e\n\x06\x43odigo\x18\x01 \x01(\t\x12\x0c\n\x04Nome\x18\x02 \x01(\t\x12\x11\n\tProfessor\x18\x03 \x01(\t\x12\x11\n\tCod_curso\x18\x04 \x01(\x05\"l\n\tMatricula\x12\n\n\x02RA\x18\x01 \x01(\x05\x12\x16\n\x0e\x43od_disciplina\x18\x02 \x01(\t\x12\x0b\n\x03\x41no\x18\x03 \x01(\x05\x12\x10\n\x08Semestre\x18\x04 \x01(\x05\x12\x0c\n\x04Nota\x18\x05 \x01(\x02\x12\x0e\n\x06\x46\x61ltas\x18\x06 \x01(\x05\x42\nZ\x08\x63lasses/b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010classes/'
  _ALUNO._serialized_start=17
  _ALUNO._serialized_end=86
  _CURSO._serialized_start=88
  _CURSO._serialized_end=121
  _DISCIPLINA._serialized_start=123
  _DISCIPLINA._serialized_end=203
  _MATRICULA._serialized_start=205
  _MATRICULA._serialized_end=313
# @@protoc_insertion_point(module_scope)
