// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: aluno.proto

package Classes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Aluno struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RA       int32  `protobuf:"varint,1,opt,name=RA,proto3" json:"RA,omitempty"`
	Nome     string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Periodo  int32  `protobuf:"varint,3,opt,name=periodo,proto3" json:"periodo,omitempty"`
	CodCurso int32  `protobuf:"varint,4,opt,name=cod_curso,json=codCurso,proto3" json:"cod_curso,omitempty"`
}

func (x *Aluno) Reset() {
	*x = Aluno{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aluno_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Aluno) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aluno) ProtoMessage() {}

func (x *Aluno) ProtoReflect() protoreflect.Message {
	mi := &file_aluno_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aluno.ProtoReflect.Descriptor instead.
func (*Aluno) Descriptor() ([]byte, []int) {
	return file_aluno_proto_rawDescGZIP(), []int{0}
}

func (x *Aluno) GetRA() int32 {
	if x != nil {
		return x.RA
	}
	return 0
}

func (x *Aluno) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Aluno) GetPeriodo() int32 {
	if x != nil {
		return x.Periodo
	}
	return 0
}

func (x *Aluno) GetCodCurso() int32 {
	if x != nil {
		return x.CodCurso
	}
	return 0
}

var File_aluno_proto protoreflect.FileDescriptor

var file_aluno_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x6c, 0x75, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a,
	0x05, 0x41, 0x6c, 0x75, 0x6e, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x52, 0x41, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x52, 0x41, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x5f, 0x63, 0x75, 0x72, 0x73,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aluno_proto_rawDescOnce sync.Once
	file_aluno_proto_rawDescData = file_aluno_proto_rawDesc
)

func file_aluno_proto_rawDescGZIP() []byte {
	file_aluno_proto_rawDescOnce.Do(func() {
		file_aluno_proto_rawDescData = protoimpl.X.CompressGZIP(file_aluno_proto_rawDescData)
	})
	return file_aluno_proto_rawDescData
}

var file_aluno_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aluno_proto_goTypes = []interface{}{
	(*Aluno)(nil), // 0: Aluno
}
var file_aluno_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aluno_proto_init() }
func file_aluno_proto_init() {
	if File_aluno_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aluno_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Aluno); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aluno_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aluno_proto_goTypes,
		DependencyIndexes: file_aluno_proto_depIdxs,
		MessageInfos:      file_aluno_proto_msgTypes,
	}.Build()
	File_aluno_proto = out.File
	file_aluno_proto_rawDesc = nil
	file_aluno_proto_goTypes = nil
	file_aluno_proto_depIdxs = nil
}
